---
title: Nutrição Escolar
author: Gabriel de Jesus Pereira
date: '`r Sys.Date()`'
execute:
  refresh: true
  warning: false
  error: false
  eval: true
  echo: true
revealjs-plugins:
  - attribution 
  - roughnotation
  - pointer
format: 
  revealjs:
    theme: [dark, style.scss]
    transition: slide
    width: 1920
    height: 1080
    background-transition: fade
    footer: "Gabriel de Jesus Pereira"
    scrollable: true
    preview-links: auto
editor:
  markdown:
    wrap: 72
lang: pt-b
---

```{r echo=FALSE}
library(dplyr)
library(GGally)
library(visdat)
library(viridis)
library(tibble)
library(factoextra)
library(ggplot2)
library(corrplot)
library(ggfortify)
```

```{r echo=FALSE}
set.seed(42)
data <- readr::read_csv("School_Nutrition_Programs_-_Meal_Reimbursement_Information_-_Program_Year_2022-2023_20240210.csv")
```


```{r echo=FALSE}
data <- data |>
  select(
        -c(ProgramYear, ReportType, CEID,
           SiteID, CountyDistrictCode, CEName,
           TDARegion, CECounty, SiteCounty,
           SiteName, ClaimDate)
  )
```

# Introdução

- Tipo de dado que está sendo utilizado no estudo

# Objetivo

# Organização dos dados

## {auto-animate="true"}

```{r}
data <- data |>
  select(
      -where(
          ~(sum(. == 0) / length(.) > 0.25)
       )
  )
```

## {auto-animate="true"}

```{r}
data <- data |>
  mutate(ESC = as.factor(ESC)) |>
  (\(x) {
    scaled_numeric <- x |> 
      select_if(is.numeric) |>
      scale()
    x |>
      select_if(~ is.character(.) | is.factor(.)) |>
      cbind(scaled_numeric) |>
      as_tibble()
    })()
```

# Análise Exploratória

## Valores ausentes

```{r echo=FALSE}
data |> 
  slice_sample(n = 1500) |> 
  vis_dat()
```

## Quantidade de classes em cada nominal

::: {.panel-tabset}

### Agência

```{r echo=FALSE}
data |> 
  ggplot(aes(x = forcats::fct_infreq(TypeOfAgency))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  scale_color_viridis(discrete = TRUE) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

### Organização

```{r echo=FALSE}
data |> 
  ggplot(aes(x = forcats::fct_infreq(TypeOfOrg))) +
  geom_bar(aes(y = (..count..) / sum(..count..))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

### Região

```{r echo=FALSE}
data |> 
  mutate(ESC = as.factor(ESC)) |>
  ggplot(aes(x = forcats::fct_infreq(ESC))) +
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

:::

# Correlação

```{r echo=FALSE}
data |>
  select_if(is.numeric) |>
  cor() |>
  corrplot(
      method="circle",
      col = mako(200),
      diag = FALSE,
      addgrid.col = "#00000040",
      tl.pos = "l",
      tl.cex = 0.6,
      tl.col = "black",
      tl.offset = 0.25,
      cl.length = 9,
      cl.cex = 0.6,
      cl.ratio = 0.25,
      family = "mono"
  )
```

# Componentes Principais

```{r echo=FALSE}
comp.p <- prcomp(data |> select_if(is.numeric), scale. = TRUE, center = TRUE, tol=0)
fviz_eig(comp.p, addlabels = TRUE, barfill="#002951")
fviz_pca_var(comp.p, col.var = "#002951",repel=TRUE)
fviz_cos2(comp.p, choice = "var", axes = 1:2, fill="#002951")
fviz_pca_var(comp.p, col.var = "cos2", title = "Biplot - Componentes principais",
             gradient.cols = c("#002951", "#eeeeee","#a0000a"), repel = TRUE)
```

# Análise Fatorial

##

```{r}
a.factorial <- factanal(data |> select_if(is.numeric), 
                        factors = 2,
                        nstart = 10)
```

##

```{r}
af.reg <- factanal(data |> select_if(is.numeric),
                   factors = 2,
                   scores="regression", 
                   nstart = 10)
```

```{r}
autoplot(af.reg,
         data = data,
         colour = "TypeOfOrg",
         label = FALSE,
         loadings = TRUE,
         loadings.colour = "#444444",
         loadings.label = TRUE,
         loadings.label.colour = "black",
         label.colour = "black",
         loadings.label.size = 5
) +
  theme_bw()
```

# Considerações Finais
