---
format: pdf
title: |
  Tabela de vida e análise de indicadores de mortalidade (censo 2022)
number-sections: false
indent: true
whitespace: small
documentclass: scrreprt
lang: pt-br
bibliography: ../includes/bib.bib
csl: ../includes/ufpe-abnt.csl
subtitle: Universidade Federal da Paraíba - CCEN
author: Gabriel de Jesus Pereira
date: today
date-format: long
highlight-style: github
fontsize: 12pt
interlinespace: 1.5pt
fig-cap-location: bottom
warning: false
echo: false
include-in-header:
  - text: |
      \usepackage{pdflscape}
      \newcommand{\blandscape}{\begin{landscape}}
      \newcommand{\elandscape}{\end{landscape}}
---


```{r}
library(lifecontingencies)
library(tidyverse)
```


```{r}
# df_obito_homem <- read_csv2('demografia/segundo_bloco/dados_relatorio3/causa_morte_homem_2022.csv') |>
#   mutate(Sexo='Homens')

# df_obito_mulher <- read_csv2('demografia/segundo_bloco/dados_relatorio3/causa_morte_mulher_2022.csv') |>
#   mutate(Sexo='Mulheres')

df_obito_homem <- read_csv2('demografia/segundo_bloco/obitos_externas_homens2022.csv') |>
  mutate(Sexo="Homens") |>
  select(-Idade) |>
  drop_na()
df_obito_mulher <- read_csv2('demografia/segundo_bloco/obitos_externas_mulheres2022.csv') |>
  mutate(Sexo="Mulheres") |>
  select(-Idade) |>
  drop_na()

df_obito <- rbind(df_obito_homem, df_obito_mulher)
df_obito[df_obito == "-"] <- "0"
df_obito <- df_obito |>
  # mutate(across(-c("Causa - CID-BR-10", "Sexo"), as.integer)) |>
  pivot_longer(
    cols = contains("ano"),
    names_to = "Idade",
    values_to = "Óbitos_externos"
  )  |>
  mutate(Idade = str_replace(Idade, "Menor de 1 ano", "Menor 1 ano"))
```


```{r}
df_populacao <- readxl::read_xlsx('demografia/segundo_bloco/dados_relatorio3/populacao_2022_rj_mulher_homem.xlsx') |>
  mutate(
    `1 a 4 anos` = `0 a 4 anos` - `Menos de 1 ano`,
    `20 a 29 anos` = `20 a 24 anos` + `25 a 29 anos`,
    `30 a 39 anos` = `30 a 34 anos` + `35 a 39 anos`,
    `40 a 49 anos` = `40 a 44 anos` + `45 a 49 anos`,
    `50 a 59 anos` = `50 a 54 anos` + `55 a 59 anos`,
    `60 a 69 anos` = `60 a 64 anos` + `65 a 69 anos`,
    `60 a 69 anos` = `60 a 64 anos` + `65 a 69 anos`,
    `70 a 79 anos` = `70 a 74 anos` + `75 a 79 anos`,
    `80 anos e mais` = `80 a 84 anos` + `85 a 89 anos` + `90 a 94 anos` + `95 a 99 anos` + `100 anos ou mais`
  ) |>
  select(
    -c(
      `0 a 4 anos`, `20 a 24 anos`,
      `25 a 29 anos`, `30 a 34 anos`,
      `35 a 39 anos`, `40 a 44 anos`,
      `45 a 49 anos`, `50 a 54 anos`,
      `55 a 59 anos`, `60 a 64 anos`,
      `65 a 69 anos`, `70 a 74 anos`,
      `75 a 79 anos`, `80 a 84 anos`,
      `85 a 89 anos`, `90 a 94 anos`,
      `95 a 99 anos`, `100 anos ou mais`)
  ) |>
  rename(`Menor 1 ano` = `Menos de 1 ano`) |>
  pivot_longer(
    cols = contains("ano"),
    names_to = "Idade",
    values_to = "População"
  )

```

```{r}
df_obito_total <- read_csv2('demografia/segundo_bloco/obito_masculino_feminino_2022.csv') |>
  pivot_longer(
    cols = contains("ano"),
    names_to = "Idade",
    values_to = "Óbitos_totais"
  ) |>
  left_join(df_obito)
```

```{r}
df_tabuanormal <- df_obito_total |>
  left_join(df_populacao) |>
  mutate(
    Mx = Óbitos_totais / População,
    M0 = ifelse(Idade == c("Menor 1 ano", "1 a 4 anos"), Mx, NA),
    ax = case_when(
      Sexo == "Homens" & Idade == "Menor 1 ano" ~ ifelse(M0 >= .107, .33, .045 + 2.684 * M0),
      Sexo == "Mulheres" & Idade == "Menor 1 ano" ~ ifelse(M0 >= .107, .35, .053 + 2.8 * M0),
      Sexo == "Homens" & Idade == "1 a 4 anos" ~ ifelse(M0 >= .107, 1.352, 1.651 + 2.816 * M0),
      Sexo == "Mulheres" & Idade == "1 a 4 anos" ~ ifelse(M0 >= .107, 1.361, 1.522 + 1.518 * M0),
      TRUE ~ .5
    ),
    amplitude = case_when(
      Idade == "Menor 1 ano" ~ 1,
      Idade == "1 a 4 anos" ~ 3,
      Idade == "5 a 9 anos" ~ 4,
      Idade == "10 a 14 anos" ~ 4,
      Idade == "15 a 19 anos" ~ 4,
      TRUE ~ 9,
    ),
    qi = case_when(
      Idade == "80 anos e mais" ~ 1,
      TRUE ~ amplitude * Mx / (1 + amplitude * (1 - ax) * Mx)
    ),
    Ix = ifelse(Idade == "Menor 1 ano", 100000, NA))


for (sex in unique(df_tabuanormal$Sexo)) {
  df_sex = df_tabuanormal[df_tabuanormal$Sexo == sex,]
  for (x in 1:(nrow(df_sex) - 1)) {
    df_sex$Ix[x + 1] = (1 - df_sex$qi[x]) * df_sex$Ix[x]
  }
  df_tabuanormal[df_tabuanormal$Sexo == sex,] = df_sex
}

df_tabuanormal <- df_tabuanormal |>
  mutate(
    dx = Ix * qi,
    Lx = NA)

for (sex in unique(df_tabuanormal$Sexo)) {
  df_sex = df_tabuanormal[df_tabuanormal$Sexo == sex,]
  for (x in 1:(nrow(df_sex))) {
    if (df_sex$ax[x] != .5) {
      df_sex$Lx[x] <- df_sex$amplitude[x] * (df_sex$Ix[x] - df_sex$dx[x]) + df_sex$dx[x] * (1 - df_sex$ax[x]) * df_sex$amplitude[x]
    } else {
      df_sex$Lx[x] = df_sex$amplitude[x] * (2 * df_sex$Ix[x] - df_sex$dx[x]) / 2
    }
  }
  df_tabuanormal[df_tabuanormal$Sexo == sex,] = df_sex
}

df_tabuanormal <- df_tabuanormal |>
  group_by(Sexo) |>
  mutate(
    Tx = rev(cumsum(rev(Lx))),
    ex = Tx / Ix) |>
  select(-c(qi, dx, ax, amplitude, M0, Mx))
```

```{r}
df <- df_obito_total |>
  left_join(df_populacao) |>
  mutate(
    Mx = Óbitos_totais / População,
    M0 = ifelse(Idade == c("Menor 1 ano", "1 a 4 anos"), Mx, NA),
    desconto = 1 - Óbitos_externos / Óbitos_totais,
    ax = case_when(
      Sexo == "Homens" & Idade == "Menor 1 ano" ~ ifelse(M0 >= .107, .33, .045 + 2.684 * M0),
      Sexo == "Mulheres" & Idade == "Menor 1 ano" ~ ifelse(M0 >= .107, .35, .053 + 2.8 * M0),
      Sexo == "Homens" & Idade == "1 a 4 anos" ~ ifelse(M0 >= .107, 1.352, 1.651 + 2.816 * M0),
      Sexo == "Mulheres" & Idade == "1 a 4 anos" ~ ifelse(M0 >= .107, 1.361, 1.522 + 1.518 * M0),
      TRUE ~ .5
    ),
    amplitude = case_when(
      Idade == "Menor 1 ano" ~ 1,
      Idade == "1 a 4 anos" ~ 3,
      Idade == "5 a 9 anos" ~ 4,
      Idade == "10 a 14 anos" ~ 4,
      Idade == "15 a 19 anos" ~ 4,
      TRUE ~ 9,
    ),
    pi = case_when(
      Idade == "80 anos e mais" ~ 0,
      TRUE ~ (1 - (1 - ax) * amplitude * Mx) / (1 + ax * amplitude * Mx)
    ),
    qi = 1 - pi ^ desconto,
    Ix = ifelse(Idade == "Menor 1 ano", 100000, NA))


for (sex in unique(df$Sexo)) {
  df_sex = df[df$Sexo == sex,]
  for (x in 1:(nrow(df_sex) - 1)) {
    df_sex$Ix[x + 1] = (1 - df_sex$qi[x]) * df_sex$Ix[x]
  }
  df[df$Sexo == sex,] = df_sex
}

df <- df |>
  mutate(
    dx = Ix * qi,
    Lx = NA)

for (sex in unique(df$Sexo)) {
  df_sex = df[df$Sexo == sex,]
  for (x in 1:(nrow(df_sex))) {
    if (df_sex$ax[x] != .5) {
      df_sex$Lx[x] <- df_sex$amplitude[x] * (df_sex$Ix[x] - df_sex$dx[x]) + df_sex$dx[x] * (1 - df_sex$ax[x]) * df_sex$amplitude[x]
    } else {
      df_sex$Lx[x] = df_sex$amplitude[x] * (2 * df_sex$Ix[x] - df_sex$dx[x]) / 2
    }
  }
  df[df$Sexo == sex,] = df_sex
}

df <- df |>
  group_by(Sexo) |>
  mutate(
    Tx = rev(cumsum(rev(Lx))),
    ex = Tx / Ix) #|>
  # select(-c(pi, qi, dx, ax, amplitude, M0, Mx, desconto))
```
