---
title: Análise do ICMS do Estado do Rio de Janeiro
author: Gabriel de Jesus Pereira
Date: 'today'
execute:
  refresh: true
  warning: false
  error: false
  eval: true
  echo: true
revealjs-plugins:
  - attribution 
  - roughnotation
  - pointer
format: 
  revealjs:
    theme: [default, style.scss]
    embed-resources: true
    transition: slide
    background-transition: fade
    scrollable: true
    preview-links: auto
editor:
  markdown:
    wrap: 72
lang: pt-br
---

```{r echo=FALSE, warning=FALSE}
library(modeltime)
library(deflateBR)
library(tseries)
library(rlang)
library(stats)
library(forecast)
library(seastests)
library(tidyverse)
library(timetk)
```

## Carregando a série temporal

```{r}
dados <- readxl::read_xls("ipeadata[15-03-2024-10-52].xls") |> 
  mutate(
    Data = paste0(Data, ".01") |> 
      as.Date(format = "%Y.%m.%d"),
    Mês = factor(month(Data, label = TRUE)),
    Ano = year(Data)
    ) |> 
  filter(Ano >= 2000) |> 
  mutate(Ano = factor(Ano))
```

Os dados são do ICMS do estado do Rio de Janeiro, coletados no período de janeiro de 1993 a dezembro de 2023.

# Análise exploratória

## A série temporal sem deflação

::: {.panel-tabset}

### Código

```{r output=FALSE}
Nao_deflacionado <- dados |> 
  plot_time_series(
    Data, 
    ICMS,
    .interactive = TRUE,
    .title = ""
    )
```

### Sem deflação

```{r echo=FALSE}
Nao_deflacionado
```

:::

## A Série temporal com deflação

::: {.panel-tabset}

### Código

```{r output=FALSE}
dados <- deflate(dados$ICMS, dados$Data, "12/2023", "igpm") |> 
  ts(start = c(2000, 1), frequency = 12) |> 
  (\(x) {
    tibble(
      Data = time(x) |>
        zoo::as.Date(),
      ICMS = c(as.matrix(x))
      ) |> 
      mutate(
        Ano = factor(year(Data)),
        Mês = factor(month(Data, label = TRUE))
      )
  })()

Deflacionado <- dados |> 
  plot_time_series(
    Data, 
    ICMS,
    .interactive = TRUE,
    .title = ""
    )
```

### Com deflação

```{r echo=FALSE}
Deflacionado
```

:::

## Análise dos meses

::: {.panel-tabset}

### Código

```{r output=FALSE}
Meses <- dados |> 
  ggplot(
    aes(
      x = Mês, 
      y = `ICMS` / 1000000, 
      group = Ano,
      color = Ano
      )
    ) +
  geom_line() +
  theme_bw() +
  labs(y = "Arrecadação do ICMS (milhões)", x = "") +
  scale_color_manual(values = viridis::mako(33))
```

### Meses de cada ano

```{r echo=FALSE}
Meses
```
:::
