---
format: pdf
title: |
  Análise Demográfica do Estado do Rio de Janeiro

  \Large Mortalidade, Natalidade e População - 2010 a 2020
# subtitle: Mortalidade, Natalidade e População - 2010 a 2020
number-sections: false
indent: true
whitespace: small
documentclass: scrreprt
lang: pt-br
bibliography: ../includes/bib.bib
csl: ../includes/ufpe-abnt.csl
subtitle: Universidade Federal da Paraíba - CCEN
author: Gabriel de Jesus Pereira
date: today
date-format: long
highlight-style: github
fontsize: 12pt
interlinespace: 1.5pt
fig-cap-location: bottom
warning: false
echo: false
include-in-header:
  - text: |
      \usepackage{pdflscape}
      \newcommand{\blandscape}{\begin{landscape}}
      \newcommand{\elandscape}{\end{landscape}}
---



# Introdução

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
```

\ \ \ O estado do Rio de Janeiro, localizado na região Sudeste do Brasil, é um dos estados mais importantes do país, tanto em termos econômicos quanto culturais. Com uma área de aproximadamente 43.696 km², o Rio de Janeiro é o terceiro menor estado brasileiro, mas também é um dos mais populosos. De acordo com o censo de 2022, 16.055.174 pessoas viviam no estado do Rio de Janeiro.

\vspace{12pt}

\ \ \ Apesar de sua grandeza e importância, o estado do Rio de Janeiro também enfrenta desafios significativos, como problemas relacionados à segurança pública, desigualdade social, e dificuldades econômicas. No entanto, o estado continua a ser um pilar fundamental na construção da identidade e do desenvolvimento do Brasil.

\vspace{12pt}

\ \ \ Assim, esse trabalho tem como objetivo analisar variáveis demográficas de mortalidade, natalidade e população do estado do Rio de Janeiro entre o ano de 2010 a 2020. Além disso, o trabalho também pretende testar diferentes métodos para projeção de população por sexo e comparar com as projeções reais disponibilizadas pelo IBGE.

# Metodologia

## Recursos computacionais

\ \ \ As análises a seguir foram realizadas utilizando a linguagem de programação Python [@van1995python], com a biblioteca Pandas [@reback2020pandas] para manipulação de dados e Matplotlib para visualização [@Hunter:2007]. Além disso, os documentos do relatório foram elaborados com o Quarto [@quarto], um sistema de escrita e publicação científica, e o código-fonte utilizado está disponível no GitHub [@github].

## Obtenção dos dados

\ \ \ Os dados demográficos utilizados neste estudo foram obtidos de duas fontes principais. Os dados de óbitos e nascimentos vivos foram extraídos do TABNET, uma ferramenta desenvolvida pelo DATASUS. O TABNET é um tabulador genérico de domínio público que permite a rápida organização dos dados conforme a consulta desejada, enquanto o DATASUS oferece informações valiosas para a análise da saúde pública e de variáveis demográficas, auxiliando na elaboração de programas de ações de saúde. Os dados populacionais do estado do Rio de Janeiro foram obtidos a partir de projeções do Instituto Brasileiro de Geografia e Estatística (IBGE). As informações sobre óbitos são provenientes do Sistema de Informações sobre Mortalidade (SIM), e os dados de nascimentos vivos são do Sistema de Informações sobre Nascidos Vivos (SINASC). Vale destacar que as projeções do IBGE referem-se à data de 1º de julho, e as projeções utilizadas abrangem os anos de 2011 a 2020. Além disso, o ano de 2050 foi selecionado para comparação com os métodos de projeção final. Para a comparação das diferentes técnicas de projeção, também foram utilizados os dados do IBGE referentes aos censos de 2000 e 2010

\vspace{12pt}

\ \ \ A análise abrange o período de 2010 a 2020, delimitando os dados de população, mortalidade e natalidade a esse intervalo. Os dados de mortalidade estão detalhados por município no estado do Rio de Janeiro. As projeções populacionais do IBGE incluem faixas etárias e são segmentadas por sexo, permitindo uma análise detalhada da pirâmide etária do estado.

## Análise Exploratória de Dados

\ \ \ A análise exploratória de dados é uma etapa fundamental em qualquer estudo que utilize a estatística como principal ferramenta de análise. Ela permite identificar padrões de comportamento nos dados e descobrir relações entre as variáveis estudadas. Assim, após a coleta e organização dos dados, a primeira etapa deste estudo foi a análise exploratória de dados. Essa etapa possibilitou a análise dos comportamentos de natalidade, mortalidade e crescimento populacional. Para identificar esses diferentes comportamentos, foram elaborados gráficos e tabelas.

## Estatísticas para análise demográfica

\ \ \ As estatísticas utilizadas neste trabalho para analisar a população do estado do Rio de Janeiro descrevem a situação em relação à mortalidade, natalidade e crescimento populacional. O crescimento populacional relaciona-se com a natalidade e a mortalidade e pode ser descrito principalmente de duas formas: população fechada e população aberta. Na população fechada, a estrutura populacional é alterada apenas pelos nascimentos e óbitos, sem impacto das migrações externas. Um exemplo de população fechada é a Coreia do Norte, que é isolada tanto cultural quanto populacionalmente. Em contraste, a população aberta, além das características das populações fechadas, é também afetada pela dinâmica migratória, como é o caso do estado do Rio de Janeiro. Dessa forma, o crescimento populacional de uma população aberta pode ser expresso por

$$
P_n - P_0 = N_t - O_t + I_t - E_t
$${#eq-popcres}
em que $P_0$ e $P_n$ representam a população inicial no tempo $t = 0$ e a população final no tempo $t = n$, respectivamente. $N_t$ e $O_t$ indicam o número de nascidos vivos e óbitos, respectivamente. Como a população é aberta, ela é afetada pela dinâmica migratória. Assim, a imigração e a emigração no tempo $t$ são representadas por $I_t$ e $E_t$, respectivamente. A diferença entre o número de nascidos vivos e óbitos
$$
N_t - O_t
$$
é chamada de crescimento natural, enquanto a diferença entre o número de imigrantes e emigrantes,
$$
I_t - E_t
$$
é chamada de migração líquida.

\vspace{12pt}

A expressão dada na @eq-popcres pode ser dividida por uma quantidade $P_m$, que representa o número de anos-pessoa vividos na população durante um intervalo de tempo $t$, resultando na seguinte expressão:

$$
\frac{P_n - P_0}{P_m} = \frac{N_t}{P_m} - \frac{O_t}{P_m} + \frac{I_t}{P_m} - \frac{E_t}{P_m}
$$
Cada termo da equação dividido por $P_m$ fornece diferentes estatísticas para a análise da população. Essas estatísticas serão detalhadas nas próximas seções.

### Taxa bruta de crescimento (r)

\ \ \ A taxa bruta de crescimento é calculada pela diferença entre a população final no tempo $t = n$ e a população inicial no tempo $t = 0$, dividida por $P_m$. Essa estatística indica a intensidade anual de crescimento da população residente. Sua expressão é dada por:

$$
r = \frac{P_n - P_0}{P_m}
$$

A taxa bruta de crescimento é influenciada por todas as dinâmicas populacionais, incluindo o número de nascidos vivos, óbitos e mudanças migratórias.

### Taxa bruta de natalidade (TBN)

\ \ \ A taxa bruta de natalidade expressa o número de nascidos vivos por mil habitantes ocorridos na população geral durante um determinado período. Sua definição matemática é dada por:

$$
TBN = \frac{N_t}{P_m} 1000
$$

Essa taxa é influenciada pela estrutura da população, incluindo sexo e idade, e é condicionada por fatores socioeconômicos de um país. Compreender essa taxa é essencial para dimensionar a frequência de nascimentos vivos em uma população e, por exemplo, para o planejamento de assistência materno-infantil e o desenvolvimento de políticas de saúde e educação.

### Taxa bruta de mortalidade (TBM)

\ \ \ A estatística de taxa bruta de mortalidade mede a quantidade de óbitos em uma população especifíca durante um período de tempo, em relação a população total. A sua fórmula é expressa por

$$
TBM = \frac{O_t}{P_m} 1000
$$
em que $O_t$ é o número de óbitos no tempo $t$. Além disso, a taxa bruta de mortalidade (TBM) é expressa como o número de mortes por mil habitantes. Esse indicador é crucial para avaliar a saúde de uma população, medir a eficácia dos sistemas de saúde e planejar políticas de saúde pública.

### Taxa de crescimento natural (r)

A taxa de crescimento natural é a diferença entre o TBN e o TBM, sendo expresso da seguinte forma:

$$
TCN = TBN - TBM
$$

Se a TCN for positiva, isso indica que a população está crescendo naturalmente; se for negativa, indica que a população está diminuindo.

### Taxa bruta de imigração (TBI)

A taxa bruta de imigração mede o número de pessoas que imigram para uma determinada região durante um tempo $t$, em relação à população total dessa área ou país. Ela é calculada como a divisão entre o número de imigrantes que chegaram à área e a população total no meio do período, expressa por mil habitantes por ano. Assim, tem-se

$$
TBI = \frac{I_t}{P_m} 1000
$$

Esse indicador é importante para avaliar o impacto da imigração sobre o crescimento populacional e para planejar políticas relacionadas a integração social, mercado de trabalho e outras áreas afetadas pela chegada de novos residentes.

### Taxa bruta de emigração

A taxa bruta de emigração é uma estatística demográfica que mede o número de pessoas que emigram, ou seja, deixam uma determinada área ou país para viver em outro lugar durante um período de tempo, em relação à população total dessa área ou país. A fórmula básica para calcular a taxa bruta de emigração é:

$$
TBE = \frac{E_t}{P_m} 1000
$$

A taxa bruta de emigração é expressa em número de emigrantes por mil habitantes por ano. Este indicador é usado para analisar a saída de pessoas de uma região e entender os impactos dessa saída na população, na economia e em outros aspectos sociais. Um exemplo de utilização da taxa bruta de emigração é o conflito entre Rússia e Ucrânia. A TBE pode ser utilizada para avaliar a perda de mão de obra que um país enfrenta durante o período de guerra devido à emigração para outros países.

### Taxa líquida de migração

\ \ \ A taxa líquida de imigração é a diferença entre a TBE e TBI, durante um período determinado de tempo. Essa taxa reflete o saldo migratório, ou seja, o impacto líquido da migração sobre o tamanho da população de uma região. Dessa forma, tem-se a seguinte expressão:

$$
TLM = TBE - TBI
$$

A TLM é expressa em número de pessoas por mil habitantes por ano. Um valor positivo indica que a imigração supera a emigração, resultando em um aumento populacional devido à migração. Um valor negativo indica que a emigração supera a imigração, resultando em uma diminuição populacional.

\vspace{12pt}

Este indicador é útil para entender as dinâmicas migratórias de uma região e para planejar políticas públicas que respondam às mudanças populacionais provocadas pela migração.

## Taxa média geométrica de crescimento anual

A Taxa média geométrica de crescimento anual é uma medida que mostra, em percentual, quanto uma população cresceu ao ano durante o período indicado. Essa estatística demográfica é influenciada pala dinâmica de natalidade, mortalidade e migrações. Assim, a sua expressão é dada por

$$
TGCA = \sqrt[n]{\frac{P_n}{P_0}} - 1
$$
em que $n$ denota o número de anos no período. Se o TGCA for negativo, é um indicativo que a população está descrescendo, caso contrário, está crescendo.

## Tempo de duplicação de uma população

No tempo de duplicação de uma população é pressuposto que a população será o dobro em um tempo final $n$. Dessa forma, $P_n/P_0 = 2$ e, fazendo o logaritmo da expressão anterior, temos $\ln(P_n/P_0) = 0.693$. Assim, tem-se a expressão final do tempo de duplicação de uma população

$$
\frac{0.693}{r}
$$
em que $r$ denota uma taxa de crescimento. Portanto, a tempo de duplicação é interpretado como quanto tempo levará para uma população atingir o dobro do tamanho inicial.

## Projeções populacionais

\ \ \ O resultado final deste trabalho consiste na comparação entre diferentes métodos de projeção populacional. Foram utilizados quatro métodos: aritmético, geométrico, exponencial e logístico. As projeções obtidas foram, em seguida, comparadas com as projeções do IBGE. A projeção foi realizada com base nos dados dos censos populacionais de 2000 e 2010, segmentados por sexo. A partir desses dados, projetou-se a população de 2020 com cada um dos métodos e, em seguida, utilizando a projeção de 2020, estimou-se a população de 2050.

\vspace{12pt}

\ \ \ O resultado final deste trabalho é a comparação entre diferentes métodos de projeção populacional. Foram utilizados quatro métodos: aritmético, geométrico, exponencial e logístico. As projeções obtidas foram então comparadas com as projeções do IBGE. A projeção foi realizada com base nos dados dos censos populacionais de 2000 e 2010, segmentados por sexo. Com esses dados, a população de 2020 foi projetada utilizando cada um dos métodos, e, em seguida, a partir das projeções de 2020, foi estimada a população de 2050.

### Método Aritmético

\ \ \ O primeiro método aplicado para a projeção da população foi o método aritmético. Este método assume que a taxa de mudança entre duas datas é constante ao longo do intervalo de tempo. Matematicamente, ele é definido como:

$$
P_n = P_{0} + \left(P_{0}r\right)t
$$
onde $P_{0}$ é a população inicial no instante $0$, $P_n$ é a população no instante $n$, $r$ é a taxa de crescimento e $t$ é o intervalo de tempo entre $0$ e $t$. Manipulando a equação, podemos calcular a taxa de crescimento $r$ como:

$$
r = \frac{P_n - P_{0}}{\left(P_{0}t\right)}
$$

Dessa forma, com a taxa de crescimento obtida, basta fazer a previsão para o ano que se deseja considerando o intervalo de tempo $t$.

### Método Geométrico

\ \ \ Para selecionar o método de projeção, é necessário considerar diversos fatores, como a distância da estimativa desejada e o ritmo de crescimento. Se o ritmo de crescimento for geométrico, a projeção utilizando o método geométrico é definida da seguinte forma:

$$
P_n = P_{0}\left(1 + r\right)^t
$$
em que $P_n$, $P_{0}$, $t$ e $r$ representam as mesmas variáveis do método anterior. Manipulando a equação, é possível determinar a taxa de crescimento $r$:

$$
r = 10^{\frac{1}{t}\log\left(\frac{P_n}{P_{0}}\right)} - 1
$$
Além disso, para determinar o tempo necessário para que uma população dobre seu tamanho, basta considerar $P_n = 2P_{0}$. Com isso, obtemos a seguinte expressão ao manipular a equação de projeção:

$$
t = \frac{\log2}{\log\left(1 + r\right)}
$$

### Método Exponencial

O método exponencial é útil para projetar a população quando se assume um crescimento contínuo da taxa de crescimento entre duas datas.

$$
P_n = P_{0}e^{r_e t}
$$
Assim, utilizando a expressão de sua curva, podemos calcular a taxa de crescimento de maneira semelhante aos métodos anteriores:

$$
r_e = \frac{1}{t}\log\left(\frac{P_n}{P_{0}}\right)
$$

### Método Logístico

Por último, aplicou-se o método logístico. Diferentemente dos outros métodos, o método logístico não assume uma taxa de crescimento constante ao longo do intervalo de projeção. Ele descreve uma situação em que o crescimento é rápido no início do intervalo, mas se aproxima de um valor de equilíbrio, ou até mesmo se estabiliza, no final.

\vspace{12pt}

O método logístico pressupõe três condições: Primeiro, é necessário ter dados de três populações em momentos diferentes e equidistantes ($P_0$, $P_1$, $P_2$). Segundo, assume-se que a população está sempre crescendo. Finalmente, a condição de inflexão da curva deve ser atendida, que é dada por $P_{1}^2 > P_{0}P_{2}$. Com essas condições satisfeitas, a projeção da população pode ser realizada usando a seguinte equação:

$$
P_n = \frac{P_s}{1 + ce^{Kt}}
$$
em que $P_s$ é a estimativa da população assumida como limite, $P_n$ é a população estimada para o ano $n$, e $c$ é uma constante a ser estimada que representa o intervalo de tempo entre $P_0$ e o ponto de saturação ($0$). A constante $k$, assim como $c$, também deve ser estimada. $t$ é a diferença entre o ano para o qual se deseja estimar a população e o ano do primeiro censo, tomado como referência: $t = t' - t_0$. Assim, definem-se as seguintes quantidades:

$$
P_s = \frac{2P_{0} P_{1}P_{2} - P_{1}^2\left(P_{0} + P_{2}\right)}{P_{0} P_{2} - P_{1}^2}
$$

$$
c = \frac{P_s - P_{0}}{P_{0}}
$$

$$
k = \frac{1}{t_2 - t_1}\ln\left[ \frac{P_0\left(P_s - P_{1}\right)}{P_{1}\left(P_s - P_{0}\right)} \right]
$$

Como mencionado anteriormente, $P_0$, $P_1$ e $P_2$ representam as populações em três momentos distintos, que são equidistantes entre si.

# Resultados

```{python}
censo = pd.read_csv('ibge_cnv_poprj17092745_227_107_69.csv', delimiter = ';')

mortalidade = pd.read_csv('mortalidade.csv', delimiter=';')

natalidade = pd.read_csv('natalidade.csv', delimiter=';')

cat_type = pd.api.types.CategoricalDtype(
  categories=[f"{i}-{i + 4}" for i in range(0, 89, 5)] + ["90+"],
  ordered=True
)

populacao = pd.read_excel("projecoes_pop_rj.xls")\
  .melt(
    id_vars=["Idade", "Sexo"],
    value_vars=list(range(2010, 2021)),
    var_name="Ano",
    value_name="População"
  )\
  .assign(
    Idade=lambda x: x.Idade.astype(cat_type)
  )\
  .sort_values("Idade", ascending=False)\
  .reset_index(drop=True)

dados_juntos = natalidade\
  .set_index('Ano')\
  .join(mortalidade.set_index('Ano'))\
  .join(
    populacao\
      .groupby('Ano')['População']\
      .sum()\
      .to_frame()
  )\
  .stack()\
  .to_frame()\
  .reset_index()\
  .rename(
    columns={
      'level_1': 'Tipo',
      0: 'Valores'
    }
  )
```


## Descritiva dos dados

\ \ \ A análise exploratória dos dados de mortalidade, natalidade e projeções populacionais do estado do Rio de Janeiro começou com o entendimento da estrutura dos dados disponíveis. Para isso, a distribuição dos dados foi analisada por meio de histogramas, como mostrado na @fig-parom. No primeiro gráfico à esquerda, observa-se a distribuição dos nascidos vivos no estado do Rio de Janeiro. Nota-se um crescimento no número de nascidos vivos até o ano de 2015; contudo, após 2015, esses números diminuem rapidamente, atingindo sua maior redução em 2020.

::: {#fig-parom}

```{python}
g = sns.FacetGrid(
  dados_juntos.assign(Ano=lambda x: pd.Categorical(x.Ano)),
  col='Tipo',
  sharey=False,
  sharex=False,
  legend_out=False,
  hue='Tipo',
  height=6
  )
g.map_dataframe(sns.barplot, 'Ano', 'Valores')
g.add_legend(loc='lower center', bbox_to_anchor=(1.69, -0.20), ncol=3)
g.set_ylabels('')
g.set_xlabels('')
g.set_titles('')

plt.show()
```

Gráficos de barra que mostram os nascidos vivos, óbitos e população população do estado do Rio de Janeiro entre 2011 a 2020.
:::

\ \ \ Analisando agora o histograma em cor laranja, que representa a distribuição dos óbitos, observa-se uma tendência de aumento constante no número de mortes. Embora não seja possível determinar com precisão a causa desse aumento, é importante considerar os diversos problemas sociais e de segurança pública enfrentados pelo estado do Rio de Janeiro. No entanto, ao observar o ano de 2020, destaca-se que esse período coincide com o auge da pandemia de Covid-19 no estado, o que provavelmente explica o aumento significativo no número de óbitos registrado naquele ano. Por fim, o gráfico verde, que representa a distribuição da população do estado, mostra uma tendência praticamente constante. É importante notar que, apesar da queda na natalidade e óbitos, o crescimento populacional pode estar sendo significativamente influenciado pela dinâmica migratória.

\vspace{12pt}

\ \ \ Os dois gráficos da figura @fig-py são as pirâmides etárias do estado do rio de janeiro. A pirâmide etária abaixo é do ano de 2010 e a de cima é a de 2020. É possível ver claramente o envelhecimento da população. Isso pode acontecer por diversos motivos. No caso do estado do Rio de Janeiro, um dos motivos bastantes impactantes parece ser a queda da natalidade, o que já havia sido observado no gráfico de barras anterior.

::: {#fig-py layout-nrow=2}

```{python}
#| label: fig-pop2020

demo_py = populacao.pivot(
  index=["Idade", "Ano"],
  columns="Sexo",
  values="População")\
  .reset_index()\
  .sort_values("Idade", ascending=False)\
  .assign(
    Masculino=lambda x: -x.Masculino
  )

barplot = sns.barplot(
  x="Masculino",
  y="Idade",
  data=demo_py.query("Ano == 2020"),
  order=demo_py.query("Ano == 2020").Idade,
  color="#049899",
  lw=0
  )
barplot = sns.barplot(
  x="Feminino",
  y="Idade",
  data=demo_py.query("Ano == 2020"),
  order=demo_py.query("Ano == 2020").Idade,
  color="#ED9502",
  lw=0
)

plt.xlabel("")
plt.ylabel("")
plt.xticks(
  ticks=[int(i) for i in list(range(-600_000, 800_000, 200_000))],
  labels=["600", "400", "200", "0", "200", "400", "600"]
)
plt.show()
```

```{python}
#| label: fig-pop2010

barplot = sns.barplot(
  x="Masculino",
  y="Idade",
  data=demo_py.query("Ano == 2010"),
  order=demo_py.query("Ano == 2010").Idade,
  label="Masculino",
  color="#049899",
  lw=0
  )
barplot = sns.barplot(
  x="Feminino",
  y="Idade",
  data=demo_py.query("Ano == 2010"),
  order=demo_py.query("Ano == 2010").Idade,
  label="Feminino",
  color="#ED9502",
  lw=0
)

plt.xlabel("")
plt.ylabel("")
plt.xticks(
  ticks=[int(i) for i in list(range(-600_000, 800_000, 200_000))],
  labels=["600", "400", "200", "0", "200", "400", "600"]
)
plt.legend(loc='upper center', bbox_to_anchor=(0.5, -.1), ncol=2)
plt.show()
```

Gráfico de pirâmide etária que mostra a distribuição da população (em milhares) por sexo, de acordo com os grupos de idade. O gráfico na @fig-pop2020 representa a distribuição referente ao ano de 2020, enquanto o gráfico na @fig-pop2010 refere-se ao ano de 2010.
:::

```{python eval=TRUE}
pop_2011 = dados_juntos.query('(Ano == 2011) and (Tipo == "População")').Valores.tolist()[0]
pop_2020 = dados_juntos.query('(Ano == 2020) and (Tipo == "População")').Valores.tolist()[0]
incremento_tot = pop_2020 - pop_2011
obitos_2011_2020 = dados_juntos.query('Tipo == "Óbitos"').Valores.sum()
nasc_2011_2020 = dados_juntos.query('Tipo == "Natalidade"').Valores.sum()
pop_media = dados_juntos.query('Tipo == "População"').Valores.mean()
nasc_medio = dados_juntos.query('Tipo == "Natalidade"').Valores.mean()
obito_medio = dados_juntos.query('Tipo == "Óbitos"').Valores.mean()
taxa_nata = nasc_medio / pop_media * 1000
taxa_mortalidade = obito_medio / pop_media * 1000
r = taxa_nata - taxa_mortalidade
taxa_geometrica_cresc = (pop_2020 / pop_2011) ** 10 - 1

pd.DataFrame(
  {
    'População e indicadores de crescimento demográfico': [
      'População 2011', 'População 2020', 'Incremento total',
      'Óbitos entre 2011 e 2020', 'Nascimentos entre 2011 e 2020',
      'Óbitos médios entre 2011 e 2020', 'Nascimentos médios entre 2011 e 2020', 'População média entre 2011 e 2020', 'Taxa bruta de natalidade', 'Taxa bruta de mortalidade',
      'Taxa de crescimento natural', 'Taxa média geométrica de crescimento anual (%)'
    ],
    'Estrutura conciliatória': [
      pop_2011,
      pop_2020,
      incremento_tot,
      obitos_2011_2020,
      nasc_2011_2020,
      obito_medio,
      nasc_medio,
      pop_media,
      taxa_nata,
      taxa_mortalidade,
      r,
      taxa_geometrica_cresc * 100
    ]
  }
).style.hide()
```

\ \ \ De acordo com a tabela de população e indicadores de crescimento demográfico, a taxa bruta de natalidade no estado do Rio de Janeiro é de 13,075 nascimentos por mil habitantes, enquanto a taxa de mortalidade é de 8 óbitos por mil habitantes, resultando em um crescimento natural de 4,89. Além disso, a taxa média de crescimento populacional no estado do Rio de Janeiro é de 76,66%. Por último, foi calculado o tempo de duplicação de uma população que, pela expressão anterior, pode ser calculado da seguinte forma: $0.693 / 0.048 = 14,44$. Portanto, a população será o dobro em 14,44 anos.

\newpage

## Projeção da população do estado do Rio de Janeiro para 2050

\ \ \ Nesta seção, serão apresentados os resultados das diferentes técnicas de projeção para a população do estado do Rio de Janeiro no ano de 2050. Inicialmente, foram utilizados os dados populacionais dos censos de 2000 e 2010 para projetar a população do estado em 2020. Com base nas estimativas populacionais para esses três anos, a população para 2050 foi então projetada. Abaixo está a tabela com os dados populacionais do Rio de Janeiro, por sexo, dos censos de 2000 e 2010. A projeção para 2020 foi necessária, pois não houve censo em 2020, apenas em 2022

```{python}
censo.style.hide()
```

### Resultados do método aritmético

\ \ \ Para cada um dos métodos aplicados, foram calculadas as taxas de crescimento $r$ para os sexos masculino e feminino. As taxas de crescimento resultantes são:

$$
r_M = \frac{7.625.679 - 6.900.335}{\left(6.900.335 \cdot 10\right)} = 0,0105
$$

$$
r_F = \frac{8.364.250 - 7.490.947}{\left(7.490.947 \cdot 10\right)} = 0,0116
$$
em que $r_F$ é a taxa de crescimento para o feminino e $r_M$ é a taxa para o masculino.

\ \ \ Agora, com as taxas de crescimento calculadas, podemos projetar a população para o ano de 2020 usando os dados de 2010, que é o ano mais recente disponível

$$
P_{2020-masculino} = 7.625.679 + \left(7.625.679 \cdot 0,0105\right) \cdot 10 = 8.427.270
$$

$$
P_{2020-feminino} = 8.364.250 + \left(8.364.250 \cdot 0,0116\right) \cdot 10 = 9.339.364
$$

\ \ \ Com a projeção para 2020 obtida, basta projetar a população para 2050 utilizando as mesmas taxas de crescimento calculadas para os sexos masculino e feminino. Assim, os resultados das projeções para 2050, com base nas estimativas de 2020, serão:

$$
P_{2050-masculino} = 11.084.823
$$

$$
P_{2050-feminino} = 12.605.745
$$

```{python}
def aritmetico(pop_final, pop_inicial, t):
  r = (pop_final - pop_inicial) / (pop_inicial * t)

  return lambda pop_ini_novo, t_novo: pop_ini_novo + (pop_ini_novo * r) * t_novo

masculino = aritmetico(censo.Masculino[1], censo.Masculino[0], 10)
feminino = aritmetico(censo.Feminino[1], censo.Feminino[0], 10)
masculino_2020 = masculino(censo.Masculino[1], 10)
feminino_2020 = feminino(censo.Feminino[1], 10)
masculino_2050 = masculino(masculino_2020, 30)
feminino_2050 = feminino(feminino_2020, 30)

new_data = pd.DataFrame({
    'Ano': [2020, 2050],
    'Masculino': np.ceil([masculino_2020, masculino_2050]),
    'Feminino': np.ceil([feminino_2020, feminino_2050])
})
censo_ari = pd.concat([censo, new_data])

censo_ari.style.hide()
censo_ari = censo_ari.assign(Metodo = "Aritmético")
```


### Resultados do método geométrico

\ \ \ O método geométrico foi aplicado de maneira semelhante ao método anterior. Primeiro, estimamos a taxa de crescimento para cada sexo e, em seguida, projetamos a população para 2020. Com a população projetada para 2020, utilizamos essa estimativa para projetar a população para 2050. As taxas de crescimento calculadas para cada sexo são:

$$
r_M = 10^{\frac{1}{10}\log\left(\frac{7.625.679}{6.900.335}\right)} - 1 = 0,0100
$$

$$
r_F = 10^{\frac{1}{10}\log\left(\frac{8.364.250}{7.490.947}\right)} - 1 = 0,0110
$$

Agora, basta projetar a população de 2020:

$$
P_{2020 - masculino} = 7.625.679 \left(1 + 0,01\right)^{10} =
$$

$$
P_{2020 - feminino} = 9.339.364 \left(1 + 0,011\right)^{10}
$$

\ \ \ Com as projeções para 2020 de cada sexo, podemos então estimar a população para 2050, obtendo os seguintes resultados:

$$
P_{2050 - masculino} = 11.373.966
$$

$$
P_{2050 - feminino} = 13.001.341
$$

\ \ \ Conforme mostrado nas tabelas abaixo e na tabela anterior do método aritmético, observa-se que as projeções são bastante similares (as projeções foram arredondadas para cima). No entanto, a projeção geométrica para 2050 tende a superestimar a população, enquanto a projeção aritmética apresenta um crescimento mais moderado. Além disso, o tempo necessário para dobrar a população é de aproximadamente 69,66 anos para o sexo masculino e 63,35 anos para o sexo feminino.

```{python}
def geometrico(pop_final, pop_inicial, t):
  r = 10 ** (np.log10(pop_final / pop_inicial) / t) - 1

  return lambda pop_ini_novo, t_novo: pop_ini_novo * (1 + r) ** t_novo

masculino_geo = geometrico(censo.Masculino[1], censo.Masculino[0], 10)
feminino_geo = geometrico(censo.Feminino[1], censo.Feminino[0], 10)
masculino_2020_geo = masculino_geo(censo.Masculino[1], 10)
feminino_2020_geo = feminino_geo(censo.Feminino[1], 10)
masculino_2050_geo = masculino_geo(masculino_2020_geo, 30)
feminino_2050_geo = feminino_geo(feminino_2020_geo, 30)

new_data_geo = pd.DataFrame({
    'Ano': [2020, 2050],
    'Masculino': np.ceil([masculino_2020_geo, masculino_2050_geo]),
    'Feminino': np.ceil([feminino_2020_geo, feminino_2050_geo])
})
censo_geo = pd.concat([censo, new_data_geo])

censo_geo.style.hide()
censo_geo = censo_geo.assign(Metodo = "Geométrico")
```

### Resultados do método exponencial

Como nos métodos anteriores, começamos estimando a taxa de crescimento $r_e$:

$$
r_{e,M} = \frac{1}{10}\ln\left(\frac{7.625.679}{6.900.335}\right) = 0,0099
$$

$$
r_{e,F} = \frac{1}{10}\ln\left(\frac{8.364.250}{7.490.947}\right) = 0,0110
$$
É importante notar que todos os métodos resultaram em taxas de crescimento muito próximas, o que pode explicar a semelhança nas projeções obtidas. Com essas taxas calculadas, projetamos a população para 2020:

$$
P_{2020 - masculino} = 7.625.679 \cdot e^{0,0099 \cdot 10} = 8.427.270
$$

$$
P_{2020 - feminino} = 8.364.250 \cdot e^{0,0110 \cdot 10} = 9.339.364
$$
Com base nas projeções de 2020 para cada sexo, calculamos a projeção para 2050. Assim, as projeções para 2050 são de 11.373.966 para o sexo masculino e 13.001.341 para o sexo feminino.

```{python}
def exponencial(pop_final, pop_inicial, t):
  r = np.log(pop_final / pop_inicial) / t

  return lambda pop_ini_novo, t_novo: pop_ini_novo * np.exp(r * t_novo)

masculino_exp = exponencial(censo.Masculino[1], censo.Masculino[0], 10)
feminino_exp = exponencial(censo.Feminino[1], censo.Feminino[0], 10)
masculino_2020_exp = masculino_exp(censo.Masculino[1], 10)
feminino_2020_exp = feminino_exp(censo.Feminino[1], 10)
masculino_2050_exp = masculino_exp(masculino_2020_exp, 30)
feminino_2050_exp = feminino_exp(feminino_2020_exp, 30)

new_data_exp = pd.DataFrame({
    'Ano': [2020, 2050],
    'Masculino': np.ceil([masculino_2020_exp, masculino_2050_exp]),
    'Feminino': np.ceil([feminino_2020_exp, feminino_2050_exp])
})
censo_exp = pd.concat([censo, new_data_exp])

censo_exp.style.hide()
censo_exp = censo_exp.assign(Metodo = "Exponencial")
```

### Resultados do método logístico

O método logístico não cumpriu com a condição de inflexão da curva $P_{1}^2 > P_{0} P_{2}$, o que acabou gerando alguns resultados inesperados ao se fazer a projeção utilizando esse método. No entanto, ele foi aplicado. É importante salientar que foram utilizados os dados do censo de 2000, 2010 e a projeção feita com os outros métodos para o ano de 2020. Assim, esses foram os dados utilizados para a aplicação do método logístico. Portanto, utilizando os valores de 2000, 2010 e 2020 das tabelas anteriores, obtemos as seguintes estimativas para as constantes

$$
P_{s \text{-masculino}} = -748386452196,1002 \ c_{masculino} = -108457,5390 \ k_{masculino} = 0,0019
$$

$$
P_{s \text{-feminino}} = -2662492726548.4253 \ c_{feminino} = -355429.0555 \ k_{feminino} = -0.0022
$$
Já é possível ver as inconsistências nos $P_s$ estimados pois o método não cumpre com a suposição $P_{1}^2 > P_{0} P_{2}$. Assim, chegamos a seguinte projeção para o ano de 2050, que pode ser observado na tabela abaixo.


\vspace{12pt}

A tabela abaixo contém a informação de projeção para o ano de 2050. Podemos ver que a projeção para o ano de 2050 acaba sendo menor que o ano de 2020. A causa é o não cumprimento da condição de inflexão da curva, o que acaba fazendo com que $P_s$ seja negativo e projetando a população para baixo.

::: {#fig-log}

```{python}

def logistico(p0, p1, p2, t):
  ps = (2 * p0 * p1 * p2 - (p1 ** 2) * (p0 + p2)) / (p0 * p2 - (p1 ** 2))
  c = (ps - p0) / p0
  k = np.log(p0 * (ps - p1) / (p1 * (ps - p0))) / t

  return ps / (1 + c * np.exp(k * t)), ps, c, k

pop_2050_masculino = logistico(
  censo.Masculino[0],
  censo.Masculino[1],
  8427270,
  50
  )

pop_2050_feminino = logistico(
  censo.Feminino[0],
  censo.Feminino[1],
  9339364,
  50
  )

new_data_logis = pd.DataFrame({
  'Ano': [2020, 2050],
  'Masculino': [8427270.000000, 7625679.0],
  'Feminino': [9339364.000000, 8364250.0]
})

proj_ibge = pd.DataFrame({
  'Ano': [2020, 2050],
  'Masculino': [8306271, 8790956],
  'Feminino': [9059918, 9419780]
}).assign(Metodo = "Projeção - IBGE")

censo_proj = pd.concat([censo, proj_ibge])

logis = pd.concat([censo, new_data_logis]).assign(Metodo = "Logístico")


junta_tudo = pd.concat([logis, censo_exp, censo_ari, censo_geo, proj_ibge])

pd.concat([censo, new_data_logis]).style.hide()
```

:::

\vspace{12pt}

# Conclusão

\ \ \ Durante o trabalho, foi possível observar mudanças significativas na demografia do estado do Rio de Janeiro. Um dos resultados mais evidentes é o rápido envelhecimento da população em comparação com 2010, além da queda na taxa de natalidade. A taxa bruta de natalidade no estado é de 13,075 nascimentos por mil habitantes, enquanto a taxa de mortalidade é de 8 óbitos por mil habitantes

\vspace{12pt}

\ \ \ Em relação aos diferentes métodos de projeção empregados, o método logístico foi o que mais se aproximou das projeções do IBGE para o ano de 2050, apesar de não cumprir todas as suposições. Além disso, os demais métodos também chegaram a valores bastante próximos, devido às suas taxas de crescimento semelhantes. A comparação pode ser visualizada na tabela abaixo. Embora as projeções para o ano de 2050 não tenham ficado boas, todas as projeções do ano de 2020 ficaram bastante próximas das originais do IBGE.

```{python}
junta_tudo.style.hide()
```

\newpage
